import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home({data}) {
  const [dataWithVenues, setDataWithVenues] = React.useState([]);
  React.useEffect(()=>{
    const fetchVenues = async () =>{
      const newData = await getVenues(data);
      setDataWithVenues(newData?.events)
    }
    fetchVenues()
  },[data, setDataWithVenues])

 // coge los valores del array creados con venue y filtra sólo los resultados con city San Francisco.
 const filtered = dataWithVenues.filter(ev => ev.venue?.address.city === 'San Francisco');
 const ordered = filtered.sort((a, b)=> a.start.utc - b.start.utc);
  // comprobando el estado del filtro para discernir los eventos físicos de los online.
  // declaramos que por defecto al acceder a la página muestre los eventos físicos.
  const [filterState, setFilterState] = React.useState('physicals');
  // función para comprobar el filtro y que mostrar los datos dependiendo del filtro seleccionado.
  const filteredList = () => {if (filterState === 'physicals') { 
    return ordered.map((event) => (
     <Link href={`/events/${event.id}`} key={event.id}>
     <a className={styles.card}>
     <h2 className={styles.cardTitle}>{event.name.text}</h2>
     <p className={styles.cardDate}>{new Date(event.start.utc).toLocaleDateString()} - {new Date(event.end.utc).toLocaleDateString()}</p>
     </a>
     </Link>
  ))
  } else if (filterState === 'online'); {
    return <p> oops! No upcoming online events planned. You can review our fiscal events </p>
        
  }}

  return (
    <div className={styles.container}>
      <Head>
        <title>Technical Test - Intership Program Eventbrite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
         
        <div className={styles.buttons}>
          <button onClick={() => setFilterState('physicals')} className={`${filterState === 'physicals' ? 'active' : ''} hola`}>Physicals Events</button> 
          <button onClick={() => setFilterState('online')}  className={`${filterState === 'online' ? 'active' : ''} adios`}>Online Events</button>
        </div>
        <h1 className={styles.title} data-testid='header'>Next events list:</h1>
        <div className={styles.eventList}>{filteredList()}</div>
      </main>
      </div>
  )
}
//llamamos a la API para que nos devuelva los datos en un formato json.
const PRIVATE_TOKEN = process.env.NEXT_PUBLIC_PRIVATE_TOKEN
const PRIVATE_ID_ORG = process.env.NEXT_PUBLIC_PRIVATE_ID_ORG
export async function getStaticProps () {

    try{
      const res = await fetch (`https://www.eventbriteapi.com//v3/organizations/${PRIVATE_ID_ORG}/events/?token=${PRIVATE_TOKEN}`)
      const data = await res.json()
      return {
          props: {
              data
           }
          }   
    } catch (error) {
        console.log(error)
        return error
    }
}
export const requestVenueForEvent = async (ev) => {
  try {
    const venueRequest = await fetch(`https://www.eventbriteapi.com/v3/venues/${ev.venue_id}/?token=${PRIVATE_TOKEN}`);
    const venue = await venueRequest.json();
    return venue;
}
  catch(error) {
    console.error(error)
  }
// bucle que recorre los valores de Venue y los almacena en un array para poder filtrarlos por ciudad   
}
const getVenues = async (data) => {
    for (let i = 0; i < data?.events.length; i++) {
      data.events[i].venue = await requestVenueForEvent(data.events[i]);
    }
    return data;
  }
